# Site settings
title: Startup Product Manager
email: anandrajaram@gmail.com
author: Anand Rajaram
description: "On building products that people love and use"
baseurl: ""
url: "http://www.startupproductmanager.com"
google_analytics: UA-10208278-2
animated: true
show_related_posts: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 5
sass:
  compressed: true
